# Generated by Django 4.1.13 on 2023-11-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_contact_contact_account_con_created_8bdae6_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
